### PR TITLE
Fix _.castArray signature

### PR DESCRIPTION
**Pull request by Cody157**
Fixes https://github.com/typed-typings/npm-lodash/issues/17

### CODE REVIEW

**Comment by unional** [comment]
In this case I would suggest making it two overload functions:

``` ts
    castArray<T>(value: T): T[];
    castArray<T>(values: T[]): T[];
```

what do you think?

**Comment by Cody157** [comment]
Tried out some examples to see the effects of each.

``` typescript
import * as _ from 'lodash';
const a = _.castArray('foo');
const b = _.castArray(['foo']);
const c = _.castArray('foo' as string | string[]);
const d = _.castArray(['foo'] as string[] | number);
const e = _.castArray('foo' as string | number);
const f = _.castArray<string | number>(['foo'] as string[] | number);
const g = _.castArray<string | number>('foo' as string | number);
```

I'll start by switching the order to 

``` typescript
    castArray<T>(values: T[]): T[];
    castArray<T>(value: T): T[];
```

because it needs to try to match to the array first, or it'll never look for an array

So I end up with two possible versions,
v1

``` typescript
    castArray<T>(value: T[] | T): T[];
```

and v2

``` typescript
    castArray<T>(values: T[]): T[];
    castArray<T>(value: T): T[];
```

To clarify, my expectations for inferred types are

```
a: string[]
b: string[]
c: string[]
d: (string | number)[]
e: (string | number)[]
f: (string | number)[]
g: (string | number)[]
```

I debated for a while whether d-g should be `(string | number)[]` or `string[] | number[]`, but I don't see how to do the second and I don't have a strong opinion on which is correct.

Now, v1 inferred types

```
a: string[]
b: string[]
c: string[]
d: T[] // error
Argument of type 'string[] | number' is not assignable to parameter of type 'string[] | string'.
  Type 'number' is not assignable to type 'string[] | string'.
    Type 'number' is not assignable to type 'string'.
e: T[] // error
Argument of type 'string | number' is not assignable to parameter of type 'string[] | string'.
  Type 'number' is not assignable to type 'string[] | string'.
    Type 'number' is not assignable to type 'string'.
f: (string | number)[]
g: (string | number)[]
```

v2 inferred types

```
a: string[]
b: string[]
c: (string | string[])[] // technically includes string[], but annoying.
d: (string[] | number)[] // incorrect, suggests that single string cannot be a member of the result
e: (string | number)[]
f: (string | number)[] // error
Argument of type 'string[] | number' is not assignable to parameter of type 'string | number'.
  Type 'string[]' is not assignable to type 'string | number'.
    Type 'string[]' is not assignable to type 'number'.
g: (string | number)[]
```

If we had a v3, which is just combining v1 and v2,

``` typescript
    castArray<T>(value: T[] | T): T[];
    castArray<T>(values: T[]): T[];
    castArray<T>(value: T): T[];
```

v3 inferred types

```
a: string[]
b: string[]
c: string[]
d: (string[] | number)[] // incorrect, suggests that single string cannot be a member of the result
e: (string | number)[]
f: (string | number)[]
g: (string | number)[]
```

Conclusion: 
This response started out as an incomprehensible mess of things I was trying while writing this. Hopefully it's a little better now. I also want to add that I'm pretty new to TypeScript, so I don't know what's considered standard with things like this. From the 3 suggestions we have so far (v1, v2, v3), none of them correctly infer`d`. However, v1 and v3 can get around that by declaring types with `f`. I think v3 is the most correct, but it may not be clear why it's defined that way. What do you think?

**Comment by blakeembrey** [comment]
This should stay a union. Making it an overload complicates the generic pattern matching (as seen above). The signature you currently have looks perfect, the only thing I might change is make `value` optional (seen in the docs as optional).

``` ts
castArray<T>(value?: T | T[]): T[]
```

**Comment by Cody157** [comment]
I completely missed that while doing this. Good catch.

**Comment by unional** [comment]
> This should stay a union

It is a bit subtle, but I think it would be better to separate in two signatures because the function behave differently depends on the input type (i.e. if you need to describe the function, the description would be different depends on the input type).

But union is good enough and it is better in terms of avoiding complication as shown above.

**Comment by blakeembrey** [comment]
@unional No, it shouldn't. It's subtle, but if you keep them separate you can never coerce a type like `string | string[]` or `number | string[]`. Because either the first or the second would match and you end up with a return type like `(string | string[])[]` instead of `string[]`.

**Comment by blakeembrey** [comment]
Here's an example: http://www.typescriptlang.org/play/#src=const%20x%3A%20string%20%7C%20string%5B%5D%20%3D%20%5B%5D%0A%0Afunction%20arr%20%3CT%3E%20(value%3F%3A%20T%20%7C%20T%5B%5D)%3A%20T%5B%5D%20%7B%0A%09return%20value%20as%20T%5B%5D%0A%7D%0A%0Aconst%20y%20%3D%20arr%3Cnumber%20%7C%20string%3E(x)%0A%0Afunction%20arr2%20%3CT%3E%20(value%3F%3A%20T%5B%5D)%3A%20T%5B%5D%0Afunction%20arr2%20%3CT%3E%20(value%3F%3A%20T)%3A%20T%5B%5D%0Afunction%20arr2%20%3CT%3E%20(value%3F%3A%20T%20%7C%20T%5B%5D)%3A%20T%5B%5D%20%7B%0A%09return%20value%20as%20T%5B%5D%0A%7D%0A%0Aconst%20z%20%3D%20arr2(x) - notice the types of `y` vs `z`.

**Comment by unional** [comment]
Um.......I see. That means it is kind of a necessary evil to use union in this case because of the dynamic nature of JS.

When I look at overloads, I was thinking more in C# then an JS. Seems like I have to change my mindset.

Thank! 👍

**Pull request merged**
