### PR TITLE
Add module to global

### PR DESCRIPTION
**Pull request by unional**

### CODE REVIEW

**Comment by demurgos** [comment]
Is this going to apply to any definition (event those installed as non-ambient) ?

**Comment by unional** [comment]
Nope. Only for global (ambient)

**Comment by unional** [comment]
Currently one pain point is we don't have a good way to avoid duplication of typings for ambient/non-ambient.
See https://github.com/typings/typings/issues/402

**Comment by demurgos** [comment]
> Nope. Only for global (ambient)

Ok, how will the difference be made ? Will there be a build step ?

**Comment by unional** [comment]
They are referenced separately in `typings/registry`:
https://github.com/typings/registry/blob/master/npm/lodash.json
https://github.com/typings/registry/blob/master/global/lodash.json

There is no build step.

Also there is no testing for the global typings yet.

**Comment by demurgos** [comment]
Ok, thank you.

**Comment by unional** [comment]
You are welcome. :smile:

**Comment by blakeembrey** [comment]
@unional There should be a build step. The global definition _should not_ be updated manually or separately from the regular script, otherwise it'll be forgotten.

**Comment by unional** [comment]
Any idea? I thought we need to wait for UMD

**Comment by blakeembrey** [comment]
Yes, we do to make this work properly. However, in the interim, we shouldn't manually keep two things up to date. Just make a script that copies the external module and adds the lines you need to make it a correct global definition. I assume it's not too much work, probably just wrapping it into a namespace and declaring `_` right?

**Comment by louy** [comment]
wouldn't something like this work?

``` ts
/// <reference path="../index.d.ts" />
import * as LoDash from 'lodash';
declare global {
  var _: typeof Lodash;
}
```

**Comment by blakeembrey** [comment]
References are stripped by Typings because of the existing issues with them. However, it could be a relative import instead but that was blocked by a TypeScript issue (not being able to add a new member to `declare global`, could only augment existing members).

**Comment by unional** [comment]
> not being able to add a new member to declare global, could only augment existing members

Barast mentioned that this is fixed. Don't know which version it goes into so don't know if it is available yet.

**Comment by unional** [comment]
Ref: https://github.com/Microsoft/TypeScript/pull/8104

**Pull request merged**
