### PR TITLE
Add _.fromPairs to wrapped calls

### PR DESCRIPTION
**Pull request by m1ch4ls**

### CODE REVIEW

**Comment by louy** [comment]
[Tests have failed](https://travis-ci.org/typed-typings/npm-lodash/builds/132100078#L482). Is it a different version of lodash?

> TypeError: _.fromPairs is not a function

**Comment by m1ch4ls** [comment]
[`_.fromPairs`](https://lodash.com/docs#fromPairs) exists since 4.0.0 

The test should pass, it passes locally for me. Can you restart the tests to be sure it's broken?

**Comment by louy** [comment]
I did restart. My guess is that it's one of the last few test cases like `_([]).fromPairs` that's broken.

**Comment by m1ch4ls** [comment]
The `lodash` version for tests was wrong. (It was 3.0.\* from `node_modules`) I have added `npm link ./source` to `.travis.yml`. The tests should pass now.

**Comment by louy** [comment]
I couldn't find `lodash` in `package.json` so my guess is it's a dependency of `mocha` or something. good call 👍🏻

**Pull request merged**
