### PR TITLE
_.get definition for ObjectWrappers

### PR DESCRIPTION
**Pull request by eggers**
Fixing for ImplicitObjectWrapper
Adding for ExplicitObjectWrapper

### CODE REVIEW

**Comment by unional** [comment]
How is the ExplicitObjectWrapper being use right now?

**Comment by eggers** [comment]
@unional The `ExplicitObjectWrapper` didn't have a definition for `get`. Therefore, the following code erroneously reported an error:

``` ts
const value = _.chain(obj).get('prop').value();
// error TS2339: Property 'get' does not exist on type 'LoDashExplicitObjectWrapper<any>'.
```

The definitelytyped definition also reported an error, albeit a different one:

`error TS2339: Property 'value' does not exist on type '{}'.`

**Comment by unional** [comment]
I mean I see that you add the interface but I don't see it is being used (from your change).

**Comment by eggers** [comment]
@unional I didn't add a new interface, it already existed, but didn't have a definition for .get yet. See: https://github.com/types/npm-lodash/blob/master/index.d.ts#L5976

However, I have been doing some more work and realized that my definition is actually wrong for the ImplicitWrapper, so I'll cancel this pull request.

**Pull request closed without merging**
