### PR TITLE
implement flatmap (code from dt)

### PR DESCRIPTION
**Pull request by dotob**

### CODE REVIEW

**Comment by blakeembrey** [comment]
Not a blank comment, it's whitespace. Pretty normal.

**Comment by blakeembrey** [comment]
LGTM 👍

**Comment by dotob** [comment]
no problem with the whitespace...just unexpected

**Comment by unional** [comment]
Can you ad the code also to the root index.d.ts?  That's for the npm version

**Comment by dotob** [comment]
done

**Comment by unional** [comment]
Thanks!

**Pull request merged**
